apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-alert
  namespace: monitoring
  labels:
    name: elasticsearch-alert
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: elasticsearch-alert
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-alert
  namespace: monitoring
  labels:
    app: elasticsearch-alert
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-alert
    spec:
      containers:
      - name: kibana-alert
        image: harbor.qyvideo.net/duanyifei-test/elasticsearch:6.5.0_v1
        resources:
          # keep request = limit to keep this container in guaranteed class
          requests:
            memory: 1Gi
