apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-config
  namespace: monitoring
  labels:
    name: elastalert-config
data:
  kibana.yml: |
    es_host: elasticsearch-alert
    es_port: 9200
    rules_folder: rules
    run_every:
      minutes: 1
    buffer_time:
      minutes: 1
    writeback_index: elastalert_status
    alert_time_limit:
      days: 2
---
apiVersion: v1
kind: Service
metadata:
  name: elastalert
  namespace: monitoring
  labels:
    name: elastalert
spec:
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
  selector:
    app: elastalert
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elastalert
  namespace: monitoring
  labels:
    app: elastalert
spec:
  selector:
    matchLabels:
      app: elastalert
  replicas: 1
  template:
    metadata:
      labels:
        app: elastalert
    spec:
      containers:
      - name: elastalert
        image: harbor.qyvideo.net/duanyifei-test/elastalert:v1